name: Makefile

on:
  push:
    branches: '*'
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Make
      run: make
    - name: Run
      run: main.out >> out.txt
#    - name: Check
#        run: cat out.txt
    - name: Diff
        run: diff out.txt README.md