name: Makefile

on:
  push:
    branches: '*'
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Make
        run: make
      - name: Run Topology
        run: ./main.out < Test/topology.txt
      - name: Run Remove
        run: ./main.out < Test/remove.txt
      - name: Run LSRP
        run: ./main.out < Test/lsrp.txt
          echo "Hello world"
